In [155]:
import math
import numpy as np

In [156]:
#Initializing Board Position

nQueens = 8
Board = [0 for i in range (nQueens)]

for i in range(nQueens):
    pos = np.random.randint(nQueens)
    Board[i] = pos

In [157]:
# Used for getting Board Arrangement
def getArrangement(Seq):
    Arrangement = np.chararray((nQueens, nQueens), unicode = True)
    Arrangement.fill('%')
    
    for i in range(nQueens):
        Arrangement[Seq[i], i] = 'Q'
    return Arrangement

In [158]:
print("Initial Board Sequence : \n",Board)
print("\n\nInitial Board Arrangement Corresponding to the Sequence : \n",getArrangement(Board))

Initial Board Sequence : 
 [5, 3, 7, 4, 0, 3, 0, 3]


Initial Board Arrangement Corresponding to the Sequence : 
 [['%' '%' '%' '%' 'Q' '%' 'Q' '%']
 ['%' '%' '%' '%' '%' '%' '%' '%']
 ['%' '%' '%' '%' '%' '%' '%' '%']
 ['%' 'Q' '%' '%' '%' 'Q' '%' 'Q']
 ['%' '%' '%' 'Q' '%' '%' '%' '%']
 ['Q' '%' '%' '%' '%' '%' '%' '%']
 ['%' '%' '%' '%' '%' '%' '%' '%']
 ['%' '%' 'Q' '%' '%' '%' '%' '%']]


In [159]:
#Used to give the heuristic value, i.e, No. of Queens of attacking each other directly or indirectly

def Clashes(Seq):
    
    clashes = 0
    
    #Calculating Row clashes
    row_col_clashes = abs(len(Seq) - len(np.unique(Seq)))
    clashes += 2*row_col_clashes
    #print(clashes)

    # calculate diagonal clashes
    for i in range(len(Seq)):
        for j in range(len(Seq)):
            if ( i != j):
                dx = abs(i-j)
                dy = abs(Seq[i] - Seq[j])
                if(dx == dy):
                    clashes += 1


    return clashes

In [160]:
clashes = Clashes(Board)
print("No. of Queens of attacking each other directly or indirectly(clashes), initially : ",clashes)

No. of Queens of attacking each other directly or indirectly(clashes), initially :  12


In [161]:
def initializeClashArray(Board, clashes):
    #clashArray used to take the position of queen which will help in minimizing the heuristic value
    clashArray = np.zeros((nQueens, nQueens))

    #clashes in initial Board Position
    for i in range(nQueens):
        clashArray[Board[i], i] = clashes
    return clashArray

In [162]:
clashArray = initializeClashArray(Board, clashes)

print(clashArray)
clashes

[[ 0.  0.  0.  0. 12.  0. 12.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 12.  0.  0.  0. 12.  0. 12.]
 [ 0.  0.  0. 12.  0.  0.  0.  0.]
 [12.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 12.  0.  0.  0.  0.  0.]]


12

In [163]:
iteration = 0
passes = 0

#will be used to store the indexe queen contributing to lower clashes
newrow =  newcol = -1

print("initial clashes : ",clashes)
print("initial board : : ",Board)


print("\n\n Pass No. : ",passes+1)

while clashes is not 0:
    iteration += 1
    
    #Computing Clashing Array
    for i in range(nQueens):
       
        TempBoard = Board.copy()
        
        iPosition = [i for i in range(nQueens)]
        iPosition.remove(TempBoard[i])
    
        for position in iPosition:
            TempBoard[i] = position
            
            #computing the clash Array
            clashArray[TempBoard[i], i] = Clashes(TempBoard)
    
    
    #index of the queen which will help to minimize the clashes
    newrow, newcol = np.argwhere(clashArray == np.min(clashArray))[0]
    
    #Changing the board w.r.t. to the index of that queen
    Board[newcol] = newrow
    
    #Clashes after changing the position of that queen
    clashes = Clashes(Board)
    
    #Initializing Clashing Array for new Board
    clashArray = initializeClashArray(Board, clashes)
    
    #If we found the Solution
    if clashes == 0:
        print("\n\nYay!!!, We found the solution in ",iteration," iterations and Pass No. : ",passes+1)
        print("\n The Solution is : \n")
        
        #Printing the solution
        sol = getArrangement(Board)
        for i in range(nQueens):
            for j in range(nQueens):
                print(sol[i,j],end = " ")
            print()
        
        break
    
    #Probably Stuck in local minima. So initializing Randomly again.
    if iteration == 5000:
        
        iteration = 0
        passes += 1

        print("\nNot found in 1000  iterations, Pass No. : ",passes)
        print("Board becomes : ",Board)
        print("Clashes becomes : ",clashes)
        
        print("\n\n Now Pass No. : ",passes+1)
        
        # So changing the board position randomly
        for i in range(nQueens):
            pos = np.random.randint(nQueens)
            Board[i] = pos
        clashes = Clashes(Board)
        clashArray = initializeClashArray(Board, clashes)
        
        print("So Modified Board : ", Board, " with clashes : ",clashes)
        if passes == 10:
            print("Not Found the solution in 5 passes of 1000 iterations each")
            break



        
        
    

initial clashes :  12
initial board : :  [5, 3, 7, 4, 0, 3, 0, 3]


 Pass No. :  1

Not found in 1000  iterations, Pass No. :  1
Board becomes :  [5, 1, 7, 4, 0, 3, 0, 6]
Clashes becomes :  4


 Now Pass No. :  2
So Modified Board :  [0, 0, 6, 7, 4, 4, 0, 3]  with clashes :  16

Not found in 1000  iterations, Pass No. :  2
Board becomes :  [7, 2, 6, 1, 1, 4, 0, 3]
Clashes becomes :  2


 Now Pass No. :  3
So Modified Board :  [0, 7, 1, 7, 6, 6, 2, 7]  with clashes :  12

Not found in 1000  iterations, Pass No. :  3
Board becomes :  [0, 4, 1, 7, 3, 6, 2, 5]
Clashes becomes :  2


 Now Pass No. :  4
So Modified Board :  [3, 7, 7, 0, 2, 1, 0, 6]  with clashes :  12


Yay!!!, We found the solution in  4  iterations and Pass No. :  4

 The Solution is : 

% % % Q % % % % 
% % % % % % Q % 
% % % % Q % % % 
% % Q % % % % % 
Q % % % % % % % 
% % % % % Q % % 
% % % % % % % Q 
% Q % % % % % % 
